#!/bin/bash
# TODO: move whole thing to separate TF file, to be run with admin privileges

BUCKET_NAME="terraform-remote-state-storage-mine"

echo "Creating Terraform state S3 bucket..."
aws s3 mb "s3://${BUCKET_NAME}"

echo "Enabling bucket versioning on state bucket..."
# Per TF recommendations: https://www.terraform.io/docs/backends/types/s3.html
aws s3api put-bucket-versioning \
    --bucket "${BUCKET_NAME}" \
    --versioning-configuration "Status=Enabled"

echo "Blocking all public access on state bucket..."
aws s3api put-public-access-block \
    --bucket "${BUCKET_NAME}" \
    --public-access-block-configuration \
    "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

echo "Creating Terraform DynamoDB lock table..."

# TODO: add SSE
aws dynamodb create-table \
    --table-name "terraform-lock-table" \
    --attribute-definitions "AttributeName=LockID,AttributeType=S" \
    --key-schema "AttributeName=LockID,KeyType=HASH" \
    --billing-mode "PROVISIONED" \
    --provisioned-throughput "ReadCapacityUnits=1,WriteCapacityUnits=1"
